# Generated by Django 6.1 on 2026-09-01 15:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(help_text='owner/name on GitHub', max_length=140, unique=True)),
                ('goal', models.TextField(blank=True, help_text='One sentence. What finishing this project looks like.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused on purpose'), ('shipped', 'Shipped'), ('dropped', 'Dropped')], default='active', max_length=10)),
                ('status_reason', models.CharField(blank=True, max_length=280)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('paused_until', models.DateField(blank=True, help_text='After this date a paused project starts nagging again.', null=True)),
                ('goal_set_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['repo'],
            },
        ),
        migrations.CreateModel(
            name='TriageRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
        migrations.CreateModel(
            name='TriageDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(max_length=140)),
                ('action', models.CharField(choices=[('hide', 'Made private')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=280)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='portfolio.triagerun')),
            ],
            options={
                'ordering': ['repo'],
            },
        ),
    ]
