# Generated by Django 6.1 on 2026-09-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(help_text='owner/name on GitHub', max_length=140)),
                ('week', models.CharField(help_text='ISO week label, e.g. "2026-W36"', max_length=8)),
                ('window_start', models.DateTimeField(help_text='Monday 00:00:00, local time')),
                ('window_end', models.DateTimeField(help_text='Sunday 23:59:59.999999, local time')),
                ('commits', models.PositiveIntegerField(default=0)),
                ('active_days', models.PositiveSmallIntegerField(default=0)),
                ('lines_added', models.PositiveIntegerField(default=0)),
                ('lines_removed', models.PositiveIntegerField(default=0)),
                ('files_touched', models.PositiveIntegerField(default=0)),
                ('partial', models.BooleanField(default=False, help_text='Diffstat cap (D2) exceeded - lines/files columns are an undercount.')),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['repo', 'week'],
                'constraints': [models.UniqueConstraint(fields=('repo', 'week'), name='unique_repo_week')],
            },
        ),
    ]
