# Generated by Django 6.1 on 2026-09-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_repoweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(help_text='ISO week label, e.g. "2026-W36"', max_length=8, unique=True)),
                ('markdown', models.TextField(help_text='The exact markdown the command printed/wrote to --out.')),
                ('data', models.JSONField(default=dict, help_text='Snapshot: per-repo mid-flight work, new-repos-this-week, and the focus item.')),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-week'],
            },
        ),
    ]
